name: Laravel Workflow

on: push

jobs:
  build:
    name: Laravel Build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/composer
      - uses: ./.github/actions/config-laravel
      - name: Create DB and schemas
        run: |
          cd lumen
          mkdir -p database
          touch database/database.sqlite
          php artisan migrate
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: |
          cd lumen
          vendor/bin/phpunit --testdox --stop-on-failure
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'The project test-send4-lumen-crud has been deployed.'